### ISSUE TITLE
Failures with GEOS master / 3.9

### ISSUE THREAD

**Issue by jorisvandenbossche** [pygeos/pygeos#233]
I was testing with GEOS master (in light of the new OverlayNG), and next to 2 failures related to the new overlay implementation (which I am fixing in https://github.com/pygeos/pygeos/pull/232), there are also 2 other failures:

```
_______________________________________ test_points_invalid_ndim ________________________________________

    def test_points_invalid_ndim():
        with pytest.raises(pygeos.GEOSException):
>           pygeos.points([0, 1, 2, 3])
E           Failed: DID NOT RAISE <class 'pygeos.GEOSException'>

pygeos/test/test_creation.py:41: Failed
_______________________________________ test_from_wkb_empty[POLYGON EMPTY] _____________________________

wkt = 'POLYGON EMPTY'

    @pytest.mark.parametrize(
        "wkt", ("POINT EMPTY", "LINESTRING EMPTY", "POLYGON EMPTY", "GEOMETRYCOLLECTION EMPTY")
    )
    def test_from_wkb_empty(wkt):
        wkb = pygeos.to_wkb(pygeos.Geometry(wkt))
        geom = pygeos.from_wkb(wkb)
        assert pygeos.is_geometry(geom).all()
        assert pygeos.is_empty(geom).all()
>       assert pygeos.to_wkb(geom) == wkb
E       AssertionError: assert b'\x01\x03\x0...0\x00\x00\x00' == b'\x01\x03\x0...0\x00\x00\x00'
E         At index 4 diff: b'\x80' != b'\x00'
E         Use -v to get the full diff

pygeos/test/test_io.py:121: AssertionError
```

The first case now seems to ignore the 4th dimension, and create a POINT Z:

```
(Pdb) pygeos.points([0, 1, 2, 3])
<pygeos.Geometry POINT Z (0 1 2)>
```

In the second case, the WKB of an empty polygon differs depending on whether the empty polygon was created from WKT or WKB:

```
(Pdb) geom1 = pygeos.Geometry("POLYGON EMPTY")
(Pdb) geom1
<pygeos.Geometry POLYGON EMPTY>
(Pdb) pygeos.to_wkb(geom1)
b'\x01\x03\x00\x00\x00\x00\x00\x00\x00'
(Pdb) geom2 = pygeos.from_wkb(pygeos.to_wkb(geom1))
(Pdb) geom2
<pygeos.Geometry POLYGON EMPTY>
(Pdb) pygeos.to_wkb(geom2)
b'\x01\x03\x00\x00\x80\x00\x00\x00\x00'
```

**Comment by jorisvandenbossche** [comment]
So for the WKB issue, in my example above, `geom1` gives a coordinate dimension of 2, and `geom2` of 3 (using `pygeos.get_coordinate_dimension`. But `pygeos.has_z` gives False for both.  That seems like something buggy in GEOS.

**Comment by jorisvandenbossche** [comment]
The WKB issue is already fixed by @pramsey: https://github.com/libgeos/geos/commit/fa24fb2f3bd84cd70309f8594aa29738661e94ca

**Comment by mwtoews** [comment]
The issue was somewhat describe in [GEOS Trac #1048](https://trac.osgeo.org/geos/ticket/1048). I haven't had a chance to investigate the new behaviour yet...

**Comment by jorisvandenbossche** [comment]
Note that the second issue mentioned above (the dimensionality in WKB roundtrips) is already fixed, see the commit I linked to above (I reported it on the GEOS chat channel, and Paul promptly fixed it)

The first issue is 

```
(Pdb) pygeos.points([0, 1, 2, 3])
<pygeos.Geometry POINT Z (0 1 2)>
```

while before this raised an error. This relates to this code in pygeos:

https://github.com/pygeos/pygeos/blob/2e65c2d42f4897327ec17aa1ebd58ef73c8cbf42/src/ufuncs.c#L1491-L1503

and

https://github.com/pygeos/pygeos/blob/2e65c2d42f4897327ec17aa1ebd58ef73c8cbf42/src/ufuncs.c#L26-L31

So before, this raised an error if you tried to create a Point with a 4 dimensional coord sequence, or when trying to create a 4 dimensional coord sequence (not directly sure which of the two raised the error) 

So it might be related to the changes that were done to fix the WKB/WKT dimensionality issues, but it is not about WKB/WKT itself.

**Comment by jorisvandenbossche** [comment]
So with GEOS 3.8, the error we currently get is:

```
In [19]: pygeos.points([0, 1, 2, 3])
...
GEOSException: IllegalArgumentException: Unknown ordinate index 0
```

This error comes from `setOrdinate` in GEOS: https://github.com/libgeos/geos/blob/26cd4782faf7451c7a3df6a33a462b2669ef5153/include/geos/geom/FixedSizeCoordinateSequence.h#L63-L81 
But this code itself hasn't changed since GEOS 3.8.0, so not directly sure why we don't get this error anymore when using GEOS master

**Comment by jorisvandenbossche** [comment]
Ah, got it. https://github.com/libgeos/geos/commit/8e29f768e6d8597a5568acd628712583506f9928 accidentally changed the error return value for `GEOSCoordSeq_setOrdinate_r` from 0 to 1, so we no longer catch the error. 

Should be an easy fix, can do a PR in a few days:

```patch
--- a/capi/geos_ts_c.cpp
+++ b/capi/geos_ts_c.cpp
@@ -2164,7 +2164,7 @@ extern "C" {
     GEOSCoordSeq_setOrdinate_r(GEOSContextHandle_t extHandle, CoordinateSequence* cs,
                                unsigned int idx, unsigned int dim, double val)
     {
-        return execute(extHandle, 1, [&]() {
+        return execute(extHandle, 0, [&]() {
             cs->setOrdinate(idx, dim, val);
             return 1;
         });
```

**Comment by jorisvandenbossche** [comment]
I made a small PR to fix the above explained issue: https://github.com/libgeos/geos/pull/354


But, we have a new bunch of failures: a large part of the STRtree tests are failing with GEOS master (which is about to be released). See eg https://github.com/pygeos/pygeos/runs/1465460418#step:9:86

I mailed geos-devel about it: https://lists.osgeo.org/pipermail/geos-devel/2020-November/009870.html 
I don't yet directly see what in our code could cause this ..

**Comment by caspervdw** [comment]
@jorisvandenbossche  This is solved right?

**Comment by jorisvandenbossche** [comment]
We still have a few failures on GEOS master:

```=================================== FAILURES ===================================
_____________________ [doctest] pygeos.constructive.buffer _____________________
075         Crops of 'mitre'-style joins if the point is displaced from the
076         buffered vertex by more than this limit.
077     single_sided : bool
078         Only buffer at one side of the geometry.
079 
080     Examples
081     --------
082     >>> buffer(Geometry("POINT (10 10)"), 2, quadsegs=1)
083     <pygeos.Geometry POLYGON ((12 10, 10 8, 8 10, 10 12, 12 10))>
084     >>> buffer(Geometry("POINT (10 10)"), 2, quadsegs=2)
Expected:
    <pygeos.Geometry POLYGON ((12 10, 11.4 8.59, 10 8, 8.59 8.59, 8 10, 8.59 11....>
Got:
    <pygeos.Geometry POLYGON ((12 10, 11.414 8.586, 10 8, 8.586 8.586, 8 10, 8.5...>

/home/runner/work/pygeos/pygeos/pygeos/constructive.py:84: DocTestFailure
_________________________________ test_eq_nan __________________________________

    def test_eq_nan():
>       assert point_nan != point_nan
E       assert <pygeos.Geometry POINT EMPTY> != <pygeos.Geometry POINT EMPTY>

pygeos/test/test_geometry.py:234: AssertionError
_________________________________ test_neq_nan _________________________________

    def test_neq_nan():
>       assert not (point_nan == point_nan)
E       assert not <pygeos.Geometry POINT EMPTY> == <pygeos.Geometry POINT EMPTY>

pygeos/test/test_geometry.py:238: AssertionError
_________________________________ test_set_nan _________________________________

    def test_set_nan():
        # As NaN != NaN, you can have multiple "NaN" points in a set
        # set([float("nan"), float("nan")]) also returns a set with 2 elements
        a = set(pygeos.points([[np.nan, np.nan]] * 10))
>       assert len(a) == 10  # different objects: NaN != NaN
E       assert 1 == 10
E        +  where 1 = len({<pygeos.Geometry POINT EMPTY>})

pygeos/test/test_geometry.py:245: AssertionError
______________________________ test_geos_version _______________________________

    def test_geos_version():
        expected = "{0:d}.{1:d}.{2:d}".format(*pygeos.geos_version)
>       assert pygeos.geos_version_string == expected
E       AssertionError: assert '3.10.0dev' == '3.10.0'
E         - 3.10.0
E         + 3.10.0dev
E         ?       +++

pygeos/test/test_misc.py:23: AssertionError
____________________________ test_geos_capi_version ____________________________

    @pytest.mark.skipif(
        sys.platform.startswith("win") and pygeos.geos_version[:2] == (3, 7),
        reason="GEOS_C_API_VERSION broken for GEOS 3.7.x on Windows",
    )
    def test_geos_capi_version():
        expected = "{0:d}.{1:d}.{2:d}-CAPI-{3:d}.{4:d}.{5:d}".format(
            *(pygeos.geos_version + pygeos.geos_capi_version)
        )
>       assert pygeos.geos_capi_version_string == expected
E       AssertionError: assert '3.10.0dev-CAPI-1.15.0' == '3.10.0-CAPI-1.15.0'
E         - 3.10.0-CAPI-1.15.0
E         + 3.10.0dev-CAPI-1.15.0
E         ?       +++

pygeos/test/test_misc.py:34: AssertionError
```

For the doctests, we could maybe limit ourselves to run the doctests on a single GEOS / Python combo, eg latest versions (printing precision changed in GEOS 3.10?). 

For the geos version string failures, see also https://github.com/pygeos/pygeos/pull/262#issuecomment-741716198 

The empty point / nan failures is something to further look into

**Comment by pramsey** [comment]
>  assert <pygeos.Geometry POINT EMPTY> != <pygeos.Geometry POINT EMPTY>

This seems wrong to me. It confuses the WKB representation of a thing (two nans for empty) with the thing itself (POINT EMPTY). While yes, Nan != Nan, that's not what should be tested. POINT EMPTY == POINT EMPTY. Just like LINESTRING EMPTY == LINESTRING EMPTY.

**Comment by jorisvandenbossche** [comment]
Indeed POINT EMPTY should equal POINT EMPTY. But I *assume* the test was supposed to check POINT(nan nan) != POINT(nan nan) (which I think is expected?), and something changed in the construction of POINT(nan nan).

**Comment by pramsey** [comment]
Yes, it's possible that WKB logic leaked into the constructor, I had to wrestle with POINT EMPTY WKB issues earlier.

**Comment by jorisvandenbossche** [comment]
So with GEOS 3.8 (and I assume 3.9 as well), we have:

```
In [39]: pygeos.points(np.nan, np.nan)
Out[39]: <pygeos.Geometry POINT (nan nan)>
```

But with GEOS master the above results in empty points


Or possibly related with https://github.com/libgeos/geos/commit/693c1aa855263198d42153da0d12f56b2b7a699? Which makes that POINT(nan nan) is regarded as empty

**Comment by pramsey** [comment]
The change came from a pygeos/shapely ticket... https://trac.osgeo.org/geos/ticket/1049

I dunno. It's a stupid thing to spend too much time on, as a Point(nan nan) is a fundamentally useless thing. Do we want to be able to represent it with fidelity? Do we really care how it behaves?

**Comment by caspervdw** [comment]
I am comfortable with making POINT (nan nan) convert automatically to POINT EMPTY in the constructor. Completely agree with the fact that we should not spend to much time on this. 

I will have a look at fixing our tests.

**Comment by jorisvandenbossche** [comment]
Yeah, sorry for the slow reply, and to be clear @pramsey I didn't mean to say that you should spend more time on this topic ;)

**Comment by caspervdw** [comment]
We have one failure left on GEOS master:

```
 _____________________ [doctest] pygeos.constructive.buffer _____________________
076         Crops of 'mitre'-style joins if the point is displaced from the
077         buffered vertex by more than this limit.
078     single_sided : bool
079         Only buffer at one side of the geometry.
080 
081     Examples
082     --------
083     >>> buffer(Geometry("POINT (10 10)"), 2, quadsegs=1)
084     <pygeos.Geometry POLYGON ((12 10, 10 8, 8 10, 10 12, 12 10))>
085     >>> buffer(Geometry("POINT (10 10)"), 2, quadsegs=2)
Expected:
    <pygeos.Geometry POLYGON ((12 10, 11.4 8.59, 10 8, 8.59 8.59, 8 10, 8.59 11....>
Got:
    <pygeos.Geometry POLYGON ((12 10, 11.414 8.586, 10 8, 8.586 8.586, 8 10, 8.5...>
```

Seems to be a rounding difference, maybe just in the representation.

**Comment by pramsey** [comment]
Hard to tell without seeing the whole object, but you might want to ensure the result and the expected are both normalized so you don't have failures just because of things like ordinate order.

**Comment by jorisvandenbossche** [comment]
We have a bunch of new failures with GEOS master related to the creation of LinearRings, especially with too few coordinates:

With GEOS 3.9.1, we get:

```
>>> pygeos.linearrings([(0.0, 0.0), (1.0, 1.0)])
...
GEOSException: IllegalArgumentException: Invalid number of points in LinearRing found 3 - must be 0 or >= 4
```

while with GEOS master this actually creates an (invalid?) LinearRing:

```
>>> pygeos.geos_version_string
'3.10.0dev'

>>> pygeos.linearrings([(0.0, 0.0), (1.0, 1.0)]) 
<pygeos.Geometry LINEARRING (0 0, 1 1, 0 0)>
```

Was this a deliberate change in GEOS? (in which case we probably can easily check the length ourselves and still raise an error if we want)

**Comment by jorisvandenbossche** [comment]
@pramsey this changed in https://github.com/libgeos/geos/commit/51560014f726a1f0b71e1b3a5a6ddee1d9e76c47#diff-41827735da42696d53e556926e2a31c49970245de846ac5b4169f506bcdc7f81R65 (the commit porting the new MakeValid implementation) because `MINIMUM_VALID_SIZE` was changed from 4 to 3. 
Quoting the added comment:

> A ring with 3 points is invalid, because it is collapsed and thus has a self-intersection.  It is allowed to be constructed so that it can be represented, and repaired if needed.

That seems quite deliberate ;) 
So if we want to keep disallowing creating such invalid LinearRing in the Python API, we can check the length ourselves?

**Comment by jorisvandenbossche** [comment]
Groups of failures:

- Constructing a LinearRing now accepts too few geometries (I thought we already handled that in #378?)
- `set_precision` behaviour changes in how it collapses geometries
- WKB -> geometry conversion now accepting invalid linearrings (this probably just needs a test update on our side)
- STRtree query changes with touches/crosses predicates
- Change in output for STRtree `nearest_all`

**Comment by pramsey** [comment]
How are you handling that second argument in 
```
pygeos.set_precision(pygeos.Geometry("LINESTRING (0 0, 0.1 0.1)"), 1)
```
It's the argument that determines if collapses will be kept or not. The enum in GEOS is this:
```
enum GEOSPrecisionRules {
    /** This option causes GEOSGeom_setPrecision_r() to not attempt at preserving the topology */
    GEOS_PREC_NO_TOPO = 1,
    /** This option causes GEOSGeom_setPrecision_r() to retain collapsed elements */
    GEOS_PREC_KEEP_COLLAPSED = 2
};
```
And the argument is the bitwise OR of those values together... 
```
* \param flags The bitwise OR of members of the \ref GEOSPrecisionRules enum
```
If the python wrapper is exposing the CAPI directly, maybe that '1' in the test should be a '2'? Or maybe the wrapper has its own internal mapping?

**Comment by jorisvandenbossche** [comment]
That second argument is actually the grid_size (I updated the code snippet to be explicit about that). 

But I was also just checking how we deal with those flags. With GEOS 3.10.0 I see:

```python
>>> pygeos.set_precision(pygeos.Geometry("LINESTRING (0 0, 0.1 0.1)"), grid_size=1, preserve_topology=False) 
<pygeos.Geometry LINESTRING (0 0, 0 0)>

>>> pygeos.set_precision(pygeos.Geometry("LINESTRING (0 0, 0.1 0.1)"), grid_size=1, preserve_topology=True)
<pygeos.Geometry LINESTRING Z EMPTY>
```

This `preserve_topology` keyword translates to setting the `GEOS_PREC_NO_TOPO` flag getting set or not.

We currently don't set the

**Comment by pramsey** [comment]
The behaviour is tested in https://github.com/libgeos/geos/blob/main/tests/unit/capi/GEOSGeom_setPrecisionTest.cpp, and seems to be "according to plan".

**Comment by jorisvandenbossche** [comment]
I patched pygeos for a moment to let the `preserve_topology` keyword pass through the exact value for the flag passed to `GEOSGeom_setPrecision`. For all possible values with GEOS 3.10.0:

```
In [2]: import pygeos 

In [3]: line = pygeos.Geometry("LINESTRING (0 0, 0.1 0.1)")  

In [4]: pygeos.set_precision(line, grid_size=1, preserve_topology=0) 
Out[4]: <pygeos.Geometry LINESTRING Z EMPTY>

In [5]: pygeos.set_precision(line, grid_size=1, preserve_topology=1)
Out[5]: <pygeos.Geometry LINESTRING (0 0, 0 0)>

In [6]: pygeos.set_precision(line, grid_size=1, preserve_topology=2)   
Out[6]: <pygeos.Geometry LINESTRING (0 0, 0 0)>

In [7]: pygeos.set_precision(line, grid_size=1, preserve_topology=3) 
Out[7]: <pygeos.Geometry LINESTRING (0 0, 0 0)>
```
 
and with GEOS 3.9.1:

```
In [3]: pygeos.set_precision(line, grid_size=1, preserve_topology=0)
Out[3]: <pygeos.Geometry LINESTRING Z EMPTY>

In [4]: pygeos.set_precision(line, grid_size=1, preserve_topology=1)
Out[4]: <pygeos.Geometry LINESTRING Z EMPTY>

In [5]: pygeos.set_precision(line, grid_size=1, preserve_topology=2)
Out[5]: <pygeos.Geometry LINESTRING (0 0, 0 0)>

In [6]: pygeos.set_precision(line, grid_size=1, preserve_topology=3)
Out[6]: <pygeos.Geometry LINESTRING (0 0, 0 0)>
```

So we were using `preserve_topology=False` -> `flag=1` (i.e. setting `GEOS_PREC_NO_TOPO`) as the default, which is exactly the one case that changed behaviour. 

> I'd generally get rid of "preserve topology" as an option, because what it means in entirely unclear 

Would you recommend to still set the `GEOS_PREC_NO_TOPO` as default as well?

**Comment by brendan-ward** [comment]
Right, we went with those defaults to match `simplify` purely out of an attempt at consistency, and as [you pointed out](https://github.com/pygeos/pygeos/pull/257#issuecomment-760936378) a while back we should reconsider this; we just haven't yet.  Perhaps we should consider flipping the default on `simplify` too, for the same reasons?

**Comment by pramsey** [comment]
I've added these to the doxygen, which will be more visible online shortly.

**Comment by caspervdw** [comment]
I propose exposing the 3 different modes directly to the user, with (as recommended) 0 as default option. This will be an API breakage, which is fine by me as we are still doing “experimental” releases in pygeos.

The tests should then be examined and possibly be made GEOS version dependent where the output of GEOS changed.
